services:
  graduation-checker:
    build: .
    container_name: graduation-checker-app
    ports:
      - "8080:3000"
    restart: always
    volumes:
      - ./data:/data
    environment:
      NODE_ENV: production
      PORT: 3000
      FIS_DATA_PATH: /data/course-profiles.json
