services:
  graduation-checker:
    build: .
    container_name: graduation-checker-app
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./logs:/var/log/nginx
      - ./stats:/usr/share/nginx/html/admin:ro

  admin-api:
    build: ./admin-api
    container_name: graduation-checker-admin-api
    restart: always
    volumes:
      - ./logs:/var/log/nginx:ro
      - ./stats:/stats:ro
    environment:
      - NODE_ENV=production
